use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TFoundation_Example' do
  pod 'TFoundation', :path => '../'

  target 'TFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
